services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    image: node:lts
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "yarn install && yarn run start:dev"
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://dev:devpass@postgres:5432/products
    depends_on:
      - postgres

  frontend:
    image: node:lts
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend
